# Copyright © 2017 VMware, Inc. All Rights Reserved.
---
sudo: required
language: python
cache: pip
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule
  - pip install docker
script:
  # - >
  #   sed -i.orig 's;  playbook.*;  playbook: tests/travis-playbook.yml;' molecule.yml
  - ln -s ansible-role-ansible ../ansible
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
