#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---

- name: Include OS-specific variables, Redhat not Fedora
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Fedora'

- name: Include OS-specific variables, non RedHat and/or Fedora
  include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_os_family != 'RedHat' or ansible_distribution == 'Fedora'


- name: Upgrade package cache
  shell: "{{ ansible_pachage_update }}"
  when: ansible_pachage_update is defined and update_package_cache
  changed_when: False
  tags:
    - skip_ansible_lint

- name: Install Ansible Prerequisites
  package: name={{ item }} state=present
  with_items: "{{ ansible_packages }}"

- name: Add any additional packages if defined
  apt: name={{ item }} state=present
  with_items: "{{ ansible_additional_packages }}"

- name: Assure services enabled
  service: name="{{ item }}" enabled=true
  with_items: "{{ ansible_services }}"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# retry, because sometimes we get a failure if the right pip package is already installed
- name: Install pip modules
  pip: name="{{ item }}"
  register: ansible_pip_result
  with_items: "{{ pip_modules }}"
  until: ansible_pip_result|success
  retries: 5
  delay: 1

# Separately install Ansible from pip, doing it with other modules borks now
- name: Install Ansible via pip
  pip: name="ansible"
